-- ============================================================
-- Brandora AI — Seed Data (RETIRED)
-- ============================================================
-- This file previously seeded tables that no longer exist in the ORM
-- (subscription_plans, festival_calendar, content_templates).
--
-- Schema creation AND reference-data seeding (the festival / awareness-day
-- calendar) now live in the Alembic migration:
--     backend/alembic/versions/001_initial_schema.py
--
-- To create and seed a fresh database:
--     alembic upgrade head
--
-- This file is intentionally left as a no-op and is no longer mounted into
-- the Postgres container (see docker-compose.yml).
-- ============================================================
