import Link from 'next/link'
import { Sparkles } from 'lucide-react'

export const metadata = { title: 'Terms of Service — Brandora AI' }

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background">
      <header className="border-b border-border px-6 py-4">
        <Link href="/" className="inline-flex items-center gap-2.5">
          <div className="w-8 h-8 bg-primary-600 rounded-xl flex items-center justify-center">
            <Sparkles className="w-4 h-4 text-white" />
          </div>
          <span className="font-bold text-foreground">Brandora AI</span>
        </Link>
      </header>

      <main className="max-w-3xl mx-auto px-6 py-12 space-y-8">
        <div>
          <h1 className="text-3xl font-bold text-foreground">Terms of Service</h1>
          <p className="text-muted-foreground mt-2 text-sm">Last updated: July 2025</p>
        </div>

        {[
          {
            title: '1. Acceptance of Terms',
            body: `By creating an account or using Brandora AI ("Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, you may not use the Service.`,
          },
          {
            title: '2. Description of Service',
            body: `Brandora AI is an AI-powered social media content management platform designed for NGOs, CSR teams, and social-impact organizations. The Service includes content generation, campaign scheduling, brand profile management, and social media publishing integrations.`,
          },
          {
            title: '3. User Accounts',
            body: `You are responsible for maintaining the confidentiality of your account credentials. You agree to notify us immediately of any unauthorized use of your account. You may not share your account with others or use another person's account.`,
          },
          {
            title: '4. Acceptable Use',
            body: `You agree not to use the Service to generate content that is illegal, harmful, defamatory, or violates the rights of any third party. You are solely responsible for the content you generate, publish, or distribute using the Service.`,
          },
          {
            title: '5. Intellectual Property',
            body: `Content you generate using the Service is owned by you, subject to these Terms. The Brandora AI platform, including its software, design, and underlying AI models, remains the exclusive property of Brandora AI and its licensors.`,
          },
          {
            title: '6. AI-Generated Content',
            body: `Content generated by our AI is provided on an "as is" basis. You should review all AI-generated content before publishing. We do not warrant the accuracy, completeness, or suitability of AI-generated content for any particular purpose.`,
          },
          {
            title: '7. Third-Party Integrations',
            body: `The Service integrates with third-party platforms (Meta, LinkedIn, Twitter/X). Your use of those platforms is subject to their respective terms of service. We are not responsible for changes to third-party APIs or services that may affect functionality.`,
          },
          {
            title: '8. Privacy',
            body: `Our Privacy Policy describes how we collect, use, and protect your information. By using the Service, you consent to our Privacy Policy.`,
          },
          {
            title: '9. Limitation of Liability',
            body: `To the fullest extent permitted by law, Brandora AI shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Service. Our total liability to you shall not exceed the amount you paid us in the three months preceding the claim.`,
          },
          {
            title: '10. Changes to Terms',
            body: `We may update these Terms from time to time. We will notify you of material changes by email or through the platform. Continued use of the Service after changes constitutes acceptance of the new Terms.`,
          },
          {
            title: '11. Contact',
            body: `For questions about these Terms, please contact us at legal@brandoraai.com.`,
          },
        ].map(({ title, body }) => (
          <section key={title} className="space-y-2">
            <h2 className="text-lg font-semibold text-foreground">{title}</h2>
            <p className="text-muted-foreground leading-relaxed">{body}</p>
          </section>
        ))}

        <div className="pt-4 border-t border-border flex gap-4 text-sm">
          <Link href="/privacy" className="text-primary hover:underline">Privacy Policy</Link>
          <Link href="/login" className="text-muted-foreground hover:text-foreground">Back to app</Link>
        </div>
      </main>
    </div>
  )
}
